name: Application CI

on:
  push:

env:
  DOCKER_IMAGE: voronm1522/devops:python-app
  DOCKER_TAG: latest

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 app.py

    - name: Run tests
      run: |
        python unittests.py

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: voronm1522
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}